gregkonush/lab

README.md
terraform/.terraform.lock.hcl
terraform/main.tf

- Updated Terraform provider "harvester/harvester" to version 0.6.4 with specific
constraints and hashes for secure installation.
- Enhanced documentation links for the "Experimentation Lab" to be more
descriptive and accessible.
- Introduced configuration for Home Cloud environment, including backend
connection details and resource definitions for Harvester images.

✨ Add Terraform Harvester provider configuration

---

apps/README.md
bootstrap/argo-cd.yaml
bootstrap/argo-cd/kustomization.yaml
bootstrap/cluster-resources.yaml
bootstrap/cluster-resources/in-cluster.json
bootstrap/cluster-resources/in-cluster/README.md
bootstrap/cluster-resources/in-cluster/argocd-ns.yaml
bootstrap/root.yaml
projects/README.md

Argocd bootstrap from [docs](https://argocd-autopilot.readthedocs.io/en/stable/Getting-Started/)
```bash
brew install argocd-autopilot
```
Follow docs afterwards

Argocd autopilot

---

bootstrap/argo-cd/kustomization.yaml

Make argocd insecure, grabbed from https://github.com/argoproj-labs/argocd-autopilot/blob/main/manifests/insecure/kustomization.yaml

Make argocd insecure for traefik

---

bootstrap/argo-cd/argo-cd.yaml
bootstrap/argo-cd/kustomization.yaml

Removed root.yaml file from kustomization.yaml and
removed namespace.yaml and ingress.yaml from argo-cd.yaml
as they are no longer needed.

✨ Remove unnecessary files from Argo CD bootstrap

---

apps/gitea/kustomization.yaml

Changed ROOT_URL in gitea config to use HTTPS protocol for secure connections.

✨ Update ROOT_URL to use HTTPS protocol

---

apps/ecran/kustomize/deployment.yaml
apps/ecran/kustomize/kustomization.yaml
apps/ecran/kustomize/service.yaml

This pull request updates the ecran deployment and adds a service definition for the ecran application. The deployment.yaml file is modified to include resource limits and requests for the ecran container. Additionally, a new service.yaml file is added to define the service for the ecran application, with a target port of 3000 and a port of 80.

Update ecran deployment and add service definition

---

.github/workflows/docker-build-push.yaml

This pull request adds cache configuration to the Docker build and push workflow. The cache configuration allows for faster builds by caching previously built images.

Add cache configuration to Docker build and push workflow

---

apps/ecran/kustomize/deployment.yaml

This pull request reverts the label names in the ecran-deployment file to their original values.

Revert label names

---

apps/ecran/kustomize/service.yaml

This pull request updates the ecran service definition to include ports for http and https. This allows the service to properly handle incoming requests on these ports.

Update ecran service definition to include ports for http and https

---

apps/ecran/kustomize/ingress.yaml

Added Traefik IngressRoute for ecran app to route traffic based on
Host header and enforce TLS termination.

✨ Add Traefik IngressRoute for ecran app

---

apps/gitea/kustomization.yaml
apps/sealed-secrets/kustomization.yaml
apps/templates/_application.yaml
apps/values.yaml

- Update Gitea helm chart to version 10.1.4
- Update Sealed Secrets helm chart to version 2.15.3
- Adjust application paths for Gitea, Ecran, and Sealed Secrets to match new
directory structure.

✨ Update helm chart versions and paths

---

.github/workflows/docker-build-push.yaml

This pull request updates the docker-build-push.yaml file to use the linux/arm64 platform instead of the linux/amd64 platform. This change is necessary to support ARM64 architecture.

Update docker-build-push.yaml to use linux/arm64 platform

---

.github/workflows/docker-build-push.yaml

This pull request updates the cache-to value in the docker-build-push.yaml file to use the "inline" mode instead of the "max" mode. This change ensures that the cache is properly updated during the build and push process.

Update cache-to value in docker-build-push.yaml

---

apps/ecran/kustomize/deployment.yaml
apps/ecran/kustomize/sealed-secret.yaml
apps/sealed-secrets/README.md

This pull request includes the following changes:
- Update imagePullSecrets in deployment.yaml to include the gitea-registry-credentials secret for pulling images from the Gitea registry.
- Add the gitea-registry-credentials sealed secret in sealed-secret.yaml to securely store the credentials for accessing the Gitea registry.

Update imagePullSecrets and add gitea-registry-credentials sealed secret

---

apps/ecran/kustomize/deployment.yaml

This pull request updates the imagePullPolicy and imagePullSecrets in the deployment.yaml file for the ecran application. The imagePullPolicy is set to "Always" and the imagePullSecrets is configured to use the "gitea-registry-credentials" secret. This ensures that the latest version of the ecran image is always pulled and the necessary credentials are provided for pulling the image from the registry.

Update imagePullPolicy and imagePullSecrets in deployment.yaml

---

apps/ecran/kustomize/kustomization.yaml
apps/gitea/kustomization.yaml

This pull request removes the "namespace.yaml" file from the "ecran/kustomize/kustomization.yaml" and "gitea/kustomization.yaml" files. This change ensures that the namespace file is no longer included in the deployment process.

Remove namespace.yaml from ecran/kustomize/kustomization.yaml and gitea/kustomization.yaml

---

apps/values.yaml

This pull request removes the cert-manager helm chart and namespace from the values.yaml file. This change is necessary because we no longer need cert-manager in our application.

Remove cert-manager helm chart and namespace from values.yaml

---

apps/values.yaml

This pull request removes the cert-manager and sealed-secrets paths from the apps/values.yaml file. This change is necessary to streamline the code and remove unnecessary dependencies.

Remove cert-manager and sealed-secrets from apps/values.yaml

---

apps/values.yaml

This pull request adds the cert-manager application to the apps/values.yaml file and sets its namespace to cert-manager.

Add cert-manager to apps/values.yaml and set namespace to cert-manager

---

apps/values.yaml

This pull request removes the cert-manager and sealed-secrets paths from the apps/values.yaml file. These paths are no longer needed and can be safely removed.

Refactor apps/values.yaml to remove cert-manager and sealed-secrets paths

---

apps/cert-manager/kustomization.yaml

This pull request updates the cert-manager leader election configuration in the kustomization.yaml file. The namespace for the leader election has been changed from "cert-manager" to "cert-manager".

Update cert-manager leader election configuration in kustomization.yaml

---

apps/cert-manager/kustomization.yaml

This pull request updates the cert-manager leader election configuration in the kustomization.yaml file. It removes the commented out global leaderElection namespace setting and adds references to relevant GitHub issues.

Update cert-manager leader election configuration in kustomization.yaml (#119)

---

apps/arc/kustomization.yaml

This pull request updates the arc helm chart version in the kustomization.yaml file to v0.9.1. This update ensures that the latest version of the chart is used in the deployment.

Update arc helm chart version to v0.9.1 in kustomization.yaml

---

apps/arc/kustomization.yaml

This pull request updates the arc helm chart version to v0.9.1 and adds the arc-controller and arc-runners helm charts in the kustomization.yaml file. This allows for better management of self-hosted runners with the actions-runner-controller.

Update arc helm chart version to v0.9.1 and add arc-controller and arc-runners helm charts in kustomization.yaml

---

apps/ecran/kustomize/deployment.yaml

This pull request fixes the docker image in the ecran deployment.yaml file. The image URL has been updated to point to the correct location.

🛠️ Fix docker image

---

apps/arc/action-runner-controller.yaml

This pull request updates the namespace for the arc-controller from "argocd" to "arc-controller". This change ensures consistency and aligns with the naming conventions used in the project.

🗒️ Namespace update

---

services/ecran/src/app/api/problems/route.ts
services/ecran/src/app/practice/page.tsx
services/ecran/src/app/problems/columns.tsx
services/ecran/src/app/problems/data-table.tsx
services/ecran/src/app/problems/page.tsx
services/ecran/src/app/problems/types.ts
services/ecran/src/components/practice-view.tsx
services/ecran/src/components/ui/badge.tsx
services/ecran/src/components/ui/tooltip.tsx

This pull request adds pagination functionality to the problems page, allowing users to navigate through multiple pages of problems.
- Implemented a pagination component to display page numbers and navigate between pages
- Updated the problems page to fetch and display problems based on the selected page
- Adjusted the UI to accommodate the pagination controls

feat: add pagination to problems page

---

apps/kitty-krew/src/server/routers/pod.ts

- Temporarily disabled TLS certificate validation for self-signed certificates in the pod
- This change is necessary to allow the application to connect to a server with a self-signed certificate during development or testing

feat(pod): temporarily disable TLS certificate validation for self-signed certificates

---

.github/workflows/pull-request.yml
apps/kitty-krew/src/app/routes/index.tsx
apps/kitty-krew/src/common/schemas/pod.ts

- Updated the `creationTimestamp` schema for the `Pod` resource to use the `date` type instead of the default `string` type.
- This change ensures that the `creationTimestamp` field is properly parsed and displayed as a date, providing a more accurate representation of the pod's creation time.

feat(pod): update creationTimestamp schema to use date type

---

apps/kitty-krew/src/app/routes/__root.tsx

- Conditionally render the TanStackRouterDevtools component in production environment to avoid including development tools in the production build.

feat(routes): conditionally render TanStackRouterDevtools in production

---

apps/kitty-krew/src/services/kubernetes.ts
argocd/applications/kitty-krew/overlays/dev/deployment.yaml

- Added support for using self-signed certificates when connecting to the Kubernetes API, enabling the application to work in environments where the cluster uses a self-signed certificate.

feat(kubernetes): Load Kubernetes config from cluster and use self-signed certificate

---

argocd/applications/airbyte/airbyte-values.yaml

- Fixed the ingress path for the Airbyte service
- The previous path was incorrect, causing issues with accessing the Airbyte UI

fix: fix ingress path in airbyte

---

argocd/applications/reviseur/base/deployment.yaml
argocd/applications/reviseur/base/kustomization.yaml
argocd/applications/reviseur/base/service.yaml
argocd/applications/reviseur/kustomization.yaml
argocd/applications/reviseur/overlays/dev/deployment.yaml
argocd/applications/reviseur/overlays/dev/kustomization.yaml
argocd/applications/reviseur/overlays/dev/service.yaml
packages/cloutt/kustomization/base.ts
packages/cloutt/kustomization/common/kustomization.ts
packages/cloutt/kustomization/root.ts
packages/cloutt/main.ts
packages/cloutt/package.json

- Added a new ArgoCD application for the "reviseur" service
- This allows the "reviseur" application to be deployed and managed through ArgoCD
- Provides a centralized and declarative way to deploy and manage the "reviseur" application

feat(argocd): add reviseur application

---

argocd/applications/argocd/kustomization.yaml

- Upgraded ArgoCD to version 2.14.5
- This upgrade includes bug fixes and performance improvements for the ArgoCD application
- The new version provides enhanced stability and reliability for our ArgoCD deployment
- Upgrading to the latest version ensures we have access to the latest features and security updates

feat: Upgrade ArgoCD to version 2.14.5

---

argocd/applicationsets/lovely-apps.yaml

- Added image update annotations to the Reviseur application's Argo CD manifests
- This will enable automatic image updates when a new version of the application is deployed

feat(argocd): Add image update annotations for reviseur application

---

ansible/INSTALL.md
ansible/ansible.cfg
ansible/inventory/hosts.ini
ansible/playbooks/README.md
ansible/playbooks/install_tailscale.yml
argocd/applications/tailscale/kustomization.yaml
tofu/harvester/main.tf

- Installed Tailscale on Ubuntu nodes to enable secure and private connectivity between the nodes
- Tailscale provides a simple and easy-to-use VPN solution that allows the nodes to communicate securely over the internet
- This change will improve the overall security and reliability of the network infrastructure

feat: install tailscale on ubuntu nodes

---

argocd/applications/coder/values.yaml

- Changed the coder to use a cluster type instead of the default load balancer

feat(coder): use cluster type instead of default load balancer

---

argocd/applications/reviseur/overlays/dev/deployment.yaml

- Updated the container port for the `reviseur` service from the default to `4111`.

feat(reviseur): update container port to 4111

---

argocd/applications/reviseur/base/deployment.yaml
argocd/applications/reviseur/base/service.yaml
argocd/applications/reviseur/overlays/dev/service.yaml

- Changed the container port for the `reviseur` service from the default to `4111`.

feat(reviseur): change container port to 4111

---

argocd/applications/reviseur/overlays/dev/ingress.yaml
argocd/applications/reviseur/overlays/dev/kustomization.yaml
argocd/applications/reviseur/overlays/dev/secrets.yaml

---
⧓ Review in [Butler Review `#8BpUSPJIV`](https://gitbutler.com/gregkonush/lab/reviews/8BpUSPJIV)
**feat(argocd): add sealed secret and ingress for reviseur**
- Added a sealed secret and ingress configuration for the Reviseur application in the ArgoCD deployment
- The ingress configuration provides a public-facing endpoint for accessing the Reviseur application
1 commit series (version 1)
| Series | Commit Title | Status | Reviewers | 
| --- | --- | --- | --- |
| 1/1 | [feat(argocd): add sealed secret and ingress for reviseur](https://gitbutler.com/gregkonush/lab/reviews/8BpUSPJIV/commit/766ad240-8842-4c66-9dff-122b70f574a8) | ✅ | <img width="20" height="20" src="https://avatars.githubusercontent.com/u/12027037?v=4"> |
_Please leave review feedback in the [Butler …

feat(argocd): add sealed secret and ingress for reviseur

---

.cursorignore
apps/alchimie/Dockerfile
argocd/applications/alchimie/alchimie-cluster.yaml
argocd/applications/alchimie/kustomization.yaml
argocd/applications/dagster/dagster-values.yaml

- Added a new ArgoCD application for the Alchimie service
- Updated the Dagster configuration to include the latest changes
- The Alchimie application will help manage the deployment and lifecycle of the Alchimie service
- The Dagster configuration updates ensure the data processing pipeline is up-to-date

feat(argocd): add alchimie application and update dagster config

---

argocd/applications/dagster/dagster-values.yaml

- Added a namespace parameter to the `secret` function in Dagster
- This allows users to specify a namespace for their secret references, providing more flexibility and organization
- The namespace can be used to group and manage secrets more effectively, especially in larger Dagster deployments
- This change improves the overall usability and maintainability of the Dagster secret management system

feat(dagster): add namespace to secret references

---

argocd/applications/istio-system/kustomization.yaml

- Added Istio 1.25.1 deployment configuration files
- This allows deploying the latest version of Istio to the Kubernetes cluster
- Includes configuration for the Istio control plane, sidecar injector, and various Istio components
- Enables advanced traffic management, security, and observability features provided by Istio

feat: Add Istio 1.25.1 deployment configuration

---

apps/froussard/func.yaml
argocd/applications/knative-serving/knative-serving.yaml
argocd/applications/registry/pvc.yaml

- Added a new `domain` field to the `services` model
- This allows associating each service with a specific domain or business unit

feat: add domain to services

---

argocd/applications/cert-manager/cluster-issuer-production-istio.yaml
argocd/applications/cert-manager/cluster-issuer-production-traefik.yaml
argocd/applications/cert-manager/cluster-issuer-staging-istio.yaml
argocd/applications/cert-manager/cluster-issuer-staging-traefik.yaml
argocd/applications/cert-manager/kustomization.yaml

- Added Cert-Manager ClusterIssuers for Istio and Traefik
- This allows the Istio and Traefik components to automatically request and renew SSL/TLS certificates for secure communication
- The ClusterIssuers are configured to use the Let's Encrypt ACME server for certificate provisioning
- This improves the overall security and reliability of the Istio and Traefik deployments

feat: Add Cert-Manager ClusterIssuers for Istio and Traefik

---

argocd/applications/istio-ingress/kustomization.yaml

- Updated the Istio ingress chart name from `istio-ingress` to `gateway` in the ArgoCD configuration
- This change aligns the chart name with the latest Istio terminology and naming conventions
- The purpose of this update is to ensure the ArgoCD configuration matches the Istio deployment and provides a more accurate representation of the deployed components

feat(argocd): update istio-ingress chart name to gateway

---

argocd/applications/cert-manager/kustomization.yaml

- Installed the cert-manager Helm chart to manage SSL/TLS certificates for the application
- Configured the Helm chart to automatically provision and renew Let's Encrypt certificates for the application's domains

feat: install cert-maanger with helm

---

apps/froussard/func.yaml
argocd/applications/froussard/certificate.yaml
argocd/applications/froussard/kustomization.yaml
argocd/applications/istio-ingress/kustomization.yaml

- Added a new SSL/TLS certificate to the application
- Configured an ingress to handle incoming traffic and route it to the appropriate services
- The certificate and ingress setup will improve the security and reliability of the application by providing HTTPS support and load balancing capabilities

feat: add certificate and ingress

---

argocd/applications/argocd/base/ingressroute.yaml
argocd/applications/argocd/kustomization.yaml
argocd/applications/backstage/ingressroute.yaml
argocd/applications/ecran/ingress.yaml
argocd/applications/findbobastore/ingressroute.yaml
argocd/applications/findbobastore/kustomization.yaml
argocd/applications/proompteng/ingressroute.yaml
argocd/applications/proompteng/kustomization.yaml
argocd/applications/reviseur/overlays/dev/ingressroute.yaml
argocd/applications/reviseur/overlays/dev/kustomization.yaml

- Migrated the ingress configuration to use IngressRoute instead of Ingress
- This change allows for more advanced routing capabilities provided by IngressRoute

feat(argocd): migrate ingress to ingressroute

---

apps/froussard/func.yaml
argocd/applications/froussard/gateway.yaml
argocd/applications/froussard/kustomization.yaml
argocd/applications/froussard/virtualservice.yaml
argocd/applications/knative-serving/knative-serving.yaml

- Added a new gateway and virtualservice for the froussard service in ArgoCD
- This allows the froussard service to be exposed and accessed through the cluster
- Improves the overall service mesh and routing configuration in the application

feat(argocd): add froussard gateway and virtualservice

---

argocd/applications/froussard/gateway.yaml
argocd/applications/knative-serving/knative-serving.yaml

- Removed the `local-gateways` configuration from Knative Serving
- Updated the gateway selector to use a different configuration
- This change simplifies the Knative Serving deployment and improves the overall stability and performance of the system

feat(knative-serving): remove local-gateways config and update gateway selector

---

argocd/applications/metallb-system/ipaddresspool.yaml
argocd/applications/metallb-system/l2advertisement.yaml

- Added `L2Advertisement` and `IPAddressPool` resources for MetalLB
- Implemented functionality to manage L2 advertisements and IP address pools
- Improved resource management for MetalLB deployment

feat(metallb): add L2Advertisement and IPAddressPool resources

---

tofu/harvester/.terraform.lock.hcl
tofu/harvester/main.tf

- Updated the SSH key resource to use the `id` field instead of the `name` field
- This change ensures a more reliable and unique identifier for SSH keys
- Improves the overall functionality and reliability of the harvester component

feat(harvester): update ssh key resource to use id instead of name

---

argocd/applications/metallb-system/kustomization.yaml

- Added `ipaddresspool` and `l2advertisement` resources for the MetalLB load balancer
- Implemented support for configuring IP address pools and Layer 2 advertisements
- Improved the overall functionality and flexibility of the MetalLB integration

🔧 feat(metallb): add ipaddresspool and l2advertisement resources

---

apps/froussard/func.yaml
argocd/applications/istio-ingress/external-gateway.yaml

- Disabled HTTPS on the Istio ingress gateway
- This change allows HTTP traffic to be routed through the ingress gateway
- Simplifies the configuration and setup of the ingress gateway

✨ feat: Disable HTTPS on Istio ingress gateway

---

argocd/applications/kafka/kustomization.yaml

- Enabled Kafka UI ingress to allow access to the Kafka UI
- Configured the necessary ingress rules and settings to expose the Kafka UI
- Integrated the Kafka UI with the existing infrastructure

🔧 feat: enable kafka-ui ingress

---

argocd/applications/kafka/kafbat-ui-access-kafka.yaml
argocd/applications/kafka/kustomization.yaml

- Added a network policy to allow the Kafka UI to access the Kafka cluster
- Enables the Kafka UI to communicate with the Kafka brokers
- Improves the overall accessibility and functionality of the Kafka UI

🔧 feat(kafka): Add network policy for Kafka UI to access Kafka

---

argocd/applications/kafka/application.yaml
argocd/applications/kafka/kustomization.yaml

- Added SASL authentication to the Kafka cluster in the ArgoCD deployment
- Implemented support for SASL authentication to enable secure communication with the Kafka cluster
- Configured the necessary settings and configurations to enable SASL authentication in the ArgoCD deployment

✨feat(argocd): add SASL authentication to Kafka cluster

---

argocd/applications/argocd/kustomization.yaml

Update the ArgoCD installation manifest from v2.14.5 to v2.14.11 to
take advantage of the latest bug fixes and improvements in the ArgoCD
project.

feat(argocd): update ArgoCD to v2.14.11

---

argocd/applications/knative/kustomization.yaml

Upgrade the Knative Operator from v1.17.5 to v1.18.0 to
take advantage of the latest features and bug fixes in the
Knative project.

feat(knative): Update Knative Operator to v1.18.0

---

argocd/applications/kafka/application.yaml

Upgrades the Kafka chart from version 32.2.0 to 32.2.2 to
take advantage of the latest bug fixes and improvements
in the chart.

feat(kafka): Upgrade Kafka chart to version 32.2.2

---

argocd/applications/gitea/Chart.yaml

The changes update the Gitea chart version from 11.0.0 to 11.0.1 in the
ArgoCD application manifest. This is to ensure the latest version of the
Gitea chart is deployed.

feat(gitea): Bump Gitea chart version to 11.0.1

---

argocd/applications/minio/kustomization.yaml

The Minio Operator version has been upgraded from v6.0.4 to v7.1.1.
This upgrade brings in the latest features and bug fixes from the
Minio Operator, improving the overall stability and functionality
of the Minio deployment.

feat(minio): Upgrade Minio Operator to v7.1.1

---

argocd/applications/tailscale/kustomization.yaml

Updates the Tailscale Kubernetes operator to version 1.82.5. This
version includes bug fixes and improvements to the operator, ensuring
better reliability and functionality for the Tailscale deployment.

feat(tailscale): update Tailscale operator to v1.82.5

---

argocd/applications/argocd/overlays/argocd-cdk8s-plugin.yaml
argocd/applications/argocd/plugin/cdk8s-plugin.yaml
bun.lock
packages/bonjour/README.md
packages/bonjour/cdk8s.yaml
packages/bonjour/infra/server-chart.ts
packages/bonjour/package.json

- Updated the ArgoCD plugin to use the Bun runtime instead of the previous runtime.
- This change improves the performance and reliability of the ArgoCD plugin.
- The update ensures the plugin is compatible with the latest version of ArgoCD.

fix: update argocd plugin to use bun

---

argocd/applicationsets/platform.yaml

- drop the broad Argo CD diff ignore entries for the lgtm StatefulSet
- keep only the Helm-generated pvc template apiVersion/kind churn ignored
- not run (not requested)

fix: narrow lgtm pvc diff ignore

---

argocd/applicationsets/platform.yaml

- restore targeted ignoreDifferences entries for lgtm StatefulSets
- cover k8s injected pod defaults, update strategy, and pvc status fields
- argocd app get lgtm --refresh (manual)

fix: ignore kubernetes defaults for lgtm

---

packages/bonjour/Dockerfile

- set HUSKY=0 in the builder and prod dependency stages so Docker installs no longer run husky
- docker build --target prod-deps -f packages/bonjour/Dockerfile .

fix: skip husky during bonjour docker build

---

argocd/applications/argo-workflows/ingressroute.yaml
docs/codex-workflow.md

- update the Argo Workflows IngressRoute manifest to use `traefik.io/v1alpha1`
- matches the CRD installed in the cluster to fix Argo CD sync failures
- kubectl apply --dry-run=client argocd/applications/argo-workflows/ingressroute.yaml

fix: align Argo Workflows ingressroute api group

---

argocd/applications/argo-workflows/ingressroute.yaml

- point the Traefik ingressroute at the existing argo-workflows-server service to restore traffic
- kubectl describe ingressroute argo-workflows -n argo-workflows

fix: route argo workflows ingress to server svc

---

argocd/applications/argocd/overlays/argocd-cm.yaml

- add the missing Dex issuer/storage/listener settings so Argo CD actually serves /api/dex for workflows SSO
- keep the existing static client/password wiring but enable Dex's password DB so the static entry works
- kubectl apply -f /tmp/argocd-cm.yaml
- kubectl rollout restart deployment argocd-dex-server -n argocd
- curl -sk https://argocd.proompteng.ai/api/dex/.well-known/openid-configuration

fix: configure dex issuer for workflows sso

---

argocd/applications/argocd/overlays/argocd-cm.yaml

- add the Argo CD base URL to argocd-cm so the server advertises `https://argocd.proompteng.ai`
- inline and quote the bcrypt hash Dex uses for the local admin user
- register the built-in `local` connector so Dex has a valid configuration before external IdPs are wired
- kubectl apply -k argocd/applications/argocd
- kubectl rollout restart deployment argocd-dex-server -n argocd
- curl -sk https://argocd.proompteng.ai/api/dex/.well-known/openid-configuration

fix: stabilize dex sso config

---

argocd/applications/argocd/overlays/argocd-dex-server-deployment.yaml

- drop the leftover valueFrom reference on ARGOCD_DEX_SERVER_DISABLE_TLS so Kustomize no longer renders value+valueFrom
- this unblocks Argo CD sync for the dex deployment
- kubectl kustomize argocd/applications/argocd | grep -n "ARGOCD_DEX_SERVER_DISABLE_TLS"
- kubectl apply -n argocd -f argocd/applications/argocd/overlays/argocd-dex-server-deployment.yaml

fix: remove duplicate dex env valueFrom

---

apps/froussard/Dockerfile.codex
apps/froussard/README.md
apps/froussard/scripts/build-codex-image.sh
apps/froussard/scripts/codex-bootstrap.sh
apps/froussard/scripts/codex-config-container.toml
apps/froussard/scripts/codex-plan.sh

- add a Dockerfile and helper scripts to bake the Codex CLI, bun, and GitHub auth into the automation image
- ship a reproducible config without MCP servers and document the build/push flow
- provide a bootstrap entrypoint plus a non-interactive planning script for Argo workflows
- apps/froussard/scripts/build-codex-image.sh
- docker run --rm -e CODEX_PROMPT='Draft a short bullet list for the workflow test.' -e OUTPUT_PATH=/workspace/lab/.codex-plan-test.md registry.ide-newton.ts.net/lab/codex-universal:latest /bin/bash -lc 'codex-plan.sh && cat /workspace/lab/.codex-plan-test.md'

feat: add codex automation container

---

argocd/applications/froussard/codex-image-prepull.yaml
argocd/applications/froussard/kustomization.yaml

- add a minimal DaemonSet in argo-workflows namespace that runs an init container with the codex workflow image and keeps a pause container scheduled
- update the froussard kustomization so Argo CD deploys the pre-pull DaemonSet alongside the existing resources
- ensures every node caches `registry.ide-newton.ts.net/lab/codex-universal:latest` before workflows start, reducing cold-start latency
- kubectl apply -k argocd/applications/froussard
- kubectl get pods -n argo-workflows -l app=codex-prepull
- docker run --rm ... (existing Codex planning workflow)

chore: pre-pull codex workflow image on every node

---

argocd/applications/froussard/github-codex-sensor.yaml

- add stage-filtered dependencies (`planning-event`, `implementation-event`) to the sensor definition
- use those dependency names directly in `conditions` so each trigger only fires when its stage arrives
- keep the schedule identical; no changes to workflow args or logging paths
- scripts/argo-lint.sh argocd/applications/froussard
- scripts/kubeconform.sh argocd

fix: gate codex sensor triggers with filtered conditions

---

argocd/applications/froussard/github-codex-implementation-workflow-template.yaml

- execute apps/froussard/scripts/codex-implement.sh from the synced worktree to keep implementation pods happy
- drop optional artifact output until an artifact repo is configured
- argo lint argocd/applications/froussard/github-codex-implementation-workflow-template.yaml
- kubectl apply -k argocd/applications/froussard
- argo submit tmp/debug-impl.yaml -n argo-workflows --log

fix: point implementation workflow at repo script

---

apps/froussard/Dockerfile.codex
scripts/codex-config-template.toml
scripts/sync-codex-cli.sh

- install argo and kubeconform CLIs in the Codex image so lint scripts run in automation
- configure gh auth setup-git during build to allow HTTPS pushes
- align codex config template/sync script defaults with the lab workspace
- apps/froussard/scripts/build-codex-image.sh

fix: bundle codex tooling

---

apps/froussard/Dockerfile.codex
apps/froussard/scripts/build-codex-image.sh

- add a CODEX_AUTH_CHECKSUM build arg so auth.json updates invalidate the image layer
- compute the checksum in build-codex-image.sh and forward it to docker build
- apps/froussard/scripts/build-codex-image.sh

fix: bust codex auth cache when rotating tokens

---

apps/froussard/scripts/codex-implement.sh
apps/froussard/scripts/codex-plan.sh

- replace bunx tsx with bun run for the Codex Discord relay scripts since bun can execute them directly
- keep existing logic for detecting bun and gating the relay on credentials
- n/a (relay path change only)

chore: use bun run for discord relay

---

argocd/applications/froussard/github-codex-implementation-workflow-template.yaml
argocd/applications/froussard/github-codex-planning-workflow-template.yaml

- set imagePullPolicy: Always on both codex workflow templates so pods always pull the latest image
- kubectl apply -f argocd/applications/froussard/github-codex-planning-workflow-template.yaml
- kubectl apply -f argocd/applications/froussard/github-codex-implementation-workflow-template.yaml

chore: always pull codex images
