terraform/main.tf
Added resources for kube network and VLAN configuration in preparation for setting up networking for Kubernetes clusters.
=> ✨ Add network on management cluster network as NICs are not showing up

terraform/harvester/main.tf
Introduce cloud-init configuration for Ubuntu virtual machine in Harvester.
Includes setting up Docker, SSH keys, user groups, and more.
=> ✨ Add cloud-init config for Ubuntu in Harvester

README.md, ansible/inventory/hosts.ini, ansible/playbooks/disable_firewall.yml, ansible/playbooks/rancher2.yml, ansible/playbooks/rancher_bootstrap_logs.yml, ansible/playbooks/start_rancher2_container.yml, ansible/playbooks/wait_for_rancher.yml, package.json
* Added automation playbooks for bootstrap rancher
=> ✨ Add Rancher2 deployment using ansible playbook.

terraform/harvester/.terraform.lock.hcl, terraform/harvester/main.tf
Modify the Terraform config to connect to the centralized database.
=> modify connection string

.vscode/extensions.json
Added GitHub pull request extension to recommendations in extensions.json to improve workflow and collaboration.
=> 🔧 Add GitHub pull request extension

.yamllint, bootstrap/argo-cd.yaml, bootstrap/argo-cd/ingress.yaml, bootstrap/argo-cd/kustomization.yaml, bootstrap/cluster-resources.yaml, bootstrap/root.yaml, kubernetes/README.md
* Added ingress for argocd
* Modified yamllint configuration
* Formatted bootstrapped files
=> Add argocd ingress

apps/gitea/prod/.helmignore, apps/gitea/prod/Chart.yaml
Added Gitea chart in values.yaml and Chart.yaml with version 0.0.1 and appVersion 1.16.0. Also included Gitea dependencies in Chart.yaml. Updated .helmignore to exclude unnecessary files and directories.
=> ✨ Add Gitea chart and dependencies

.gitignore, package.json, terraform/harvester/templates/load_balancer.yaml
Added load balancer configuration for Kubernetes setup to ensure smooth
operation and distribution of traffic across multiple master nodes. Also
added a new script for applying changes to the Harvester cluster using
the specified kubeconfig file.
=> feat: Add load balancer configuration for Kubernetes setup

bootstrap/argo-cd/argo-cd.yaml, bootstrap/argo-cd/kustomization.yaml, bootstrap/argo-cd/root.yaml
- Added root Application resource in root.yaml file
- Updated syncOptions to include allowEmpty=true in argo-cd.yaml and root.yaml
=> ✨ Add root Application resource and update syncOptions in Application resources

apps/gitea/app.yaml, apps/gitea/kustomization.yaml, bootstrap/argo-cd/root.yaml
Add Gitea application resource in argocd namespace with updated repo URL to
https://github.com/gregkonush/lab.git in apps/gitea/app.yaml.
=> ✨ Add Gitea application resource 🚀

bootstrap/argo-cd/root.yaml
Updated source repo URL to point to the correct repository and set target
revision to HEAD for apps directory. Adjusted destination server and namespace.
Toggled syncOptions allowEmpty to false.
=> ✨ Update root.yaml file in Argo CD

apps/gitea/application.yaml, bootstrap/argo-cd/namespace.yaml
🔄 Move gitea application to gitea namespace.
=> ✨ Add sync-wave annotation to argocd namespace.

apps/gitea/application.yaml, apps/gitea/kustomization.yaml, apps/kustomization.yaml, bootstrap/argo-cd/root.yaml
- Set allowEmpty to true in root.yaml
- Update namespace in application.yaml
- Add namespace and server in gitea application.yaml
- Add kustomize path in gitea application.yaml
=> ✨ Update Argo CD configuration

apps/gitea/application.yaml, bootstrap/argo-cd/root.yaml
Set targetRevision to main and add gitea as a component in kustomize.
#gitmoji
=> ✨ Update argo-cd root.yaml for main branch migration

apps/.helmignore, apps/Chart.yaml, apps/templates/gitea.yaml, apps/values.yaml, bootstrap/README.md, bootstrap/root.yaml
Changed namespace from 'default' to 'argocd' for better organization.
=> ✨ Update namespace in root.yaml 🏷

apps/gitea/ingress.yaml
=> add-argocd-ingress-routes

apps/gitea/kustomization.yaml
=> ✨ Add apiVersion to ingress in kustomization.yaml

apps/gitea/kustomization.yaml
=> ✨ Update valuesMerge to merge in kustomization.yaml

apps/ecran/Dockerfile, apps/ecran/next.config.mjs, apps/values.yaml
- Update Dockerfile to customize image build steps for a Next.js deployment
- Include specific commands for image compilation and production setup
=> ✨ Adjust Dockerfile for Next.js deployment

.github/workflows/docker-build-push.yaml
* Added GitHub action to build and push docker image
=> 📄 Added GitHub action

apps/ecran/kustomize/deployment.yaml
=> Added deployment for ecran

apps/ecran/src/app/page.tsx
Added a sign up form on the homepage for users to join the waitlist.
=> ✨ Add sign up form on homepage

apps/ecran/Dockerfile, scripts/docker_build_push.sh
- Change docker build to docker buildx build in order to utilize buildx features.
=> 🐳 Update docker command in docker_build_push.sh

apps/ecran/kustomize/kustomization.yaml, apps/ecran/kustomize/sealed-secret.yaml, apps/sealed-secrets/README.md
Added a sealed secret configuration for resend-api-key in the kustomization
resources to securely store and manage sensitive data.
=> ✨ Add sealed secret for resend-api-key

apps/ecran/kustomize/deployment.yaml
This pull request updates the imagePullPolicy and imagePullSecrets in the deployment.yaml file to ensure that the latest image is always pulled and the correct image pull secrets are used.
=> Update imagePullPolicy and imagePullSecrets in deployment.yaml

apps/cert-manager/kustomize.yaml, apps/ecran/kustomize/namespace.yaml, apps/gitea/kustomization.yaml, apps/gitea/namespace.yaml, apps/sealed-secrets/kustomization.yaml, apps/templates/_application.yaml, apps/values.yaml
This pull request updates the helmCharts versions for cert-manager, gitea, ecran, and sealed-secrets. It also adds and deletes namespaces for these applications.
=> Update helmCharts versions and add/delete namespaces for cert-manager, gitea, ecran, and sealed-secrets

apps/cert-manager/kustomization.yaml
This pull request updates the cert-manager helm chart values in the kustomization.yaml file. The changes include [list the specific changes made]. These updates are necessary to [explain the reason for the updates and any potential impact].
=> Update cert-manager helm chart values in kustomization.yaml

apps/cert-manager/kustomization.yaml
This pull request updates the cert-manager leader election configuration in the kustomization.yaml file. The changes include adding leader election configuration for the config and cainjector components in the cert-manager namespace.
=> Update cert-manager leader election configuration in kustomization.yaml

apps/cert-manager/kustomization.yaml, apps/values.yaml
This pull request refactors the cert-manager configuration in the kustomization.yaml and values.yaml files. It removes unnecessary leader election configurations and updates the namespace for the cert-manager application.
=> Refactor cert-manager configuration

apps/arc/arc-github-token.yaml, apps/arc/kustomization.yaml, apps/sealed-secrets/README.md, apps/values.yaml
This pull request updates the sealed-secrets README.md file and values.yaml file. It adds a new file, arc-github-token.yaml, and modifies the kustomization.yaml file to include the new file. Additionally, it makes changes to the README.md file by removing a command and adding a new command for creating a sealed secret from a secret.
=> Update sealed-secrets README.md and values.yaml

apps/arc/action-runner-controller.yaml, apps/templates/_application.yaml, apps/values.yaml
This pull request updates the arc helm chart version to v0.9.1 and adds the arc-controller and arc-runners helm charts in the kustomization.yaml file.
=> Update arc helm chart version and add arc-controller and arc-runners helm charts in kustomization.yaml

apps/templates/_application.yaml, apps/values.yaml
This pull request refactors the applicationPath handling in _application.yaml and values.yaml files. The changes ensure that the applicationPath is properly included and indented in the _application.yaml file. Additionally, a newline at the end of the values.yaml file is added for consistency.
=> Refactor applicationPath handling in _application.yaml and values.yaml

apps/values.yaml
This pull request adds the `applicationPath` for `arc/action-runner-controller.yaml` in the `apps/values.yaml` file. This change ensures that the `arc/action-runner-controller.yaml` file is included as an application in the deployment process.
=> Add applicationPath for arc/action-runner-controller.yaml in apps/values.yaml

bootstrap/argo-cd/application.yaml, bootstrap/argo-cd/kustomization.yaml
This pull request adds the Argo CD application configuration file and updates the kustomization.yaml file to include the new application.yaml file.
=> Add Argo CD application configuration and update kustomization.yaml

apps/Chart.yaml, apps/templates/_application.yaml, apps/values.yaml
This pull request removes an invalid template file and updates the version number in the Chart.yaml file.
=> Remove invalid template

apps/arc/action-runner-controller.yaml
Use example from https://github.com/argoproj/argo-cd/issues/10823
=> 🛂 Update helm chart for github action controller

apps/arc/controller/action-runner-controller.yaml, apps/arc/controller/kustomization.yaml, apps/arc/namespaces.yaml, apps/arc/runners/action-runner-sets.yaml, apps/arc/runners/kustomization.yaml, apps/values.yaml
This pull request adds the GitHub Action controller to the repository. The controller is responsible for managing GitHub Actions runners in a Kubernetes cluster. It includes the necessary YAML files and kustomization configurations for the controller and the runners.
=> 🏃🏽 Add github action controller

apps/.helmignore, apps/arc/controller/kustomization.yaml, apps/arc/runners/kustomization.yaml, package.json
This pull request removes the unnecessary kustomization files and the node_modules directory.
=> ❌ Remove kustomization

apps/ecran/kustomize/kustomization.yaml, apps/values.yaml
* Add Postgres operator
* Remove manual declaration
=> 🔧 Add helm chart for cloudnative-pg.

apps/ecran/kustomize/kustomization.yaml, apps/ecran/kustomize/postgresql.yaml
=> ✨️ Add PostgreSQL cluster to Ecran application.

kubernetes/install.sh, terraform/harvester/main.tf
- Update k3sup installation commands
- Fix Terraform configuration for SSH keys
- Set up additional servers and workers with specific configurations
=> feat: Update installation script and Terraform configuration

apps/openebs/kustomization.yaml
This pull request introduces the OpenEBS storage layer to the project. OpenEBS is a popular open-source storage platform for Kubernetes environments, providing a range of features and capabilities that can be leveraged in this project.
Some of the key features of OpenEBS that are now available include:
- Scalable and reliable storage for stateful applications
- Support for various storage engines, including hostPath, local, and dynamic provisioning
- Snapshot and cloning capabilities for easy backup and recovery
- Automated storage provisioning and management
- Integrations with popular Kubernetes storage orchestrators like Longhorn and Rook
By adding the OpenEBS storage layer, the project can now leverage these features to provide a more robust and flexible storage solution for its …
=> feat: add openebs storage layer

.gitignore, apps/ecran/ecran-deployment.yaml, pnpm-lock.yaml, services/ecran/drizzle/0005_fat_stone_men.sql, services/ecran/drizzle/meta/0005_snapshot.json, services/ecran/drizzle/meta/_journal.json, services/ecran/package.json, services/ecran/src/app/sign-up/page.tsx, services/ecran/src/db/schema.ts, services/ecran/src/lib/kubernetes.ts
- Storing the user ID when an execution is saved
=> feat: save user id with executions

pnpm-lock.yaml, services/ecran/package.json, services/ecran/src/app/api/executions/route.ts, services/ecran/src/app/api/hints/prompt.ts, services/ecran/src/app/api/hints/route.ts, services/ecran/src/app/practice/page.tsx, services/ecran/src/components/ui/hover-card.tsx, services/ecran/src/components/ui/skeleton.tsx, services/ecran/src/lib/code-executor.ts, services/ecran/src/lib/java-executor.ts, services/ecran/tailwind.config.ts
The new hint feature will provide users with guidance and tips to help them when they struggle to solve a problem.
=> feat: add a hint to practice page

.github/workflows/docker-build-push.yaml, argocd/applications/kitty-krew/base/deployment.yaml, argocd/applications/kitty-krew/kustomization.yaml, argocd/applications/kitty-krew/overlays/dev/kustomization.yaml, argocd/applications/kitty-krew/overlays/prod/kustomization.yaml, argocd/applicationsets/lovely-apps.yaml
This pull request adds a build process for the kitty-krew project. The changes include:
<###>feat: add build process for kitty-krew</###>
The new build process will allow for easier deployment and distribution of the kitty-krew application.
- Implemented a build script to package the application for distribution
- Added necessary configuration files and dependencies to support the build process
- Updated documentation to explain the new build workflow
- Streamlines the deployment of kitty-krew to various environments
- Ensures a consistent and reliable build process for the project
- Improves the overall development and release workflow for the team
=> feat: add build process for kitty-krew

argocd/applications/kitty-krew/overlays/dev/deployment.yaml, argocd/applications/kitty-krew/overlays/dev/kustomization.yaml, argocd/applications/kitty-krew/overlays/dev/secrets.yaml
This pull request adds image pull secrets and updates the deployment for the Kitty Krew application.
=> feat(kitty-krew): add image pull secrets and update deployment

argocd/applications/kitty-krew/overlays/dev/kustomization.yaml
Update kitty-krew dev environment configuration
=> feat(argocd): update kitty-krew dev environment configuration

apps/kitty-krew/app/routes/index.tsx
Add namespace filter to pod list
=> feat(pods): Add namespace filter to pod list

.github/workflows/pull-request.yml
Add conditional job execution based on changed files in the CI pipeline.
=> feat(ci): add conditional job execution based on changed files

apps/kitty-krew/Dockerfile
Optimize Dockerfile by copying only necessary files
=> feat(docker): optimize Dockerfile by copying only necessary files

apps/kitty-krew/Dockerfile
=> feat(kitty-krew): Use `vinxi build` command for production build

apps/kitty-krew/Dockerfile
=> feat: Optimize Bun build command in Kitty Krew Dockerfile

.github/workflows/docker-build-push.yaml, .github/workflows/pull-request.yml, apps/kitty-krew/.dockerignore, apps/kitty-krew/Dockerfile, apps/kitty-krew/README.md
=> feat(ci): add conditional docker builds based on changed files

apps/kitty-krew/trpc-server.handler.ts, argocd/applications/kitty-krew/overlays/dev/clusterrole.yaml, argocd/applications/kitty-krew/overlays/dev/clusterrolebinding.yaml, argocd/applications/kitty-krew/overlays/dev/deployment.yaml, argocd/applications/kitty-krew/overlays/dev/kustomization.yaml, argocd/applications/kitty-krew/overlays/dev/serviceaccount.yaml
Add service account, cluster role, and binding for kitty-krew
=> feat(k8s): Add service account, cluster role, and binding for kitty-krew

apps/kitty-krew/src/server/routers/pod.ts, apps/kitty-krew/src/utils/logger.ts
=> feat(k8s): load self-signed certificate for Kubernetes cluster

.github/PULL_REQUEST_TEMPLATE.md, apps/kitty-krew/src/server/routers/pod.ts
- Fixed a bug that caused a duplicate cluster error in the Kubernetes integration
- Improved logging to provide more detailed information for troubleshooting
N/A
=> fix: update context to fix duplicate cluster error

.github/workflows/pull-request.yml, apps/kitty-krew/biome.json, apps/kitty-krew/src/app/main.tsx, apps/kitty-krew/src/app/routeTree.gen.ts, apps/kitty-krew/src/app/router.tsx, apps/kitty-krew/src/app/routes/__root.tsx, apps/kitty-krew/src/app/routes/index.tsx, apps/kitty-krew/src/app/routes/pods.$namespace.$podName.tsx, apps/kitty-krew/src/app/routes/pods.$podName.tsx, apps/kitty-krew/src/common/schemas/pod.ts, apps/kitty-krew/src/components/spinner.tsx, apps/kitty-krew/src/server/context.ts, apps/kitty-krew/src/server/handler.ts, apps/kitty-krew/src/server/routers/_app.ts, apps/kitty-krew/src/server/routers/pod.ts, apps/kitty-krew/src/server/trpc.ts, apps/kitty-krew/src/services/kubernetes.ts, apps/kitty-krew/src/utils/logger.ts
- Added a new page to display details of a specific pod
- Implemented functionality to fetch and display pod information
- Integrated the pod details page into the application's navigation
=> feat(pod): add pod details page

apps/kitty-krew/bun.lock, apps/kitty-krew/package.json, apps/kitty-krew/src/app/routes/index.tsx, apps/kitty-krew/src/app/routes/pods.$namespace.$podName.tsx, apps/kitty-krew/src/components/multi-select.tsx, apps/kitty-krew/src/components/status-badge.tsx
- Added a namespace filter to the pods view to allow users to easily find pods in a specific namespace
- Improved the overall UI and layout of the pods view for better readability and usability
=> feat(pods): add namespace filter and improve UI

apps/kitty-krew/src/components/status-badge.tsx
- Updated the styling of the badges throughout the application
- Improved the visual appearance and consistency of the badges
=> feat: update badge styling

apps/kitty-krew/Dockerfile, apps/kitty-krew/biome.json, apps/kitty-krew/src/app/routes/pods.$namespace.$podName.tsx, apps/kitty-krew/src/server/routers/pod.ts, apps/kitty-krew/src/utils/logger.ts, argocd/applications/kitty-krew/base/deployment.yaml, argocd/applications/kitty-krew/overlays/dev/deployment.yaml
- Added log monitoring functionality to the application
- Implemented a logging system to track and analyze application logs
- Integrated a log monitoring tool to provide real-time insights and alerts
=> feat: add log monitoring

argocd/applications/kitty-krew/overlays/dev/clusterrole.yaml
- Added permission to the ClusterRole to allow viewing pod logs
=> feat(clusterrole): add permission to view pod logs

bun.lock, package.json, packages/cloutt/.gitignore, packages/cloutt/cdk8s.yaml, packages/cloutt/kustomization/base.ts, packages/cloutt/kustomization/common/deployment.ts, packages/cloutt/kustomization/common/kustomization.ts, packages/cloutt/kustomization/common/service.ts, packages/cloutt/kustomization/root.ts, packages/cloutt/main.ts, packages/cloutt/package.json, packages/cloutt/tsconfig.json
- Added a new feature to generate templates
- Implemented the necessary functionality to create and manage templates
- Improved the user experience by providing a template generation option
=> feat: add template generation

apps/reviewer/.gitignore, apps/reviewer/package.json, apps/reviewer/src/mastra/agents/github.ts, apps/reviewer/src/mastra/index.ts, apps/reviewer/src/mastra/scripts/run.ts, apps/reviewer/tsconfig.json, bun.lock, pnpm-lock.yaml
- Implemented a PR review agent that can automatically analyze pull requests and provide feedback
=> feat: Add GitHub PR review agent and tools

argocd/applications/airbyte/kustomization.yaml
- Added the Airbyte application to the ArgoCD deployment
- This will allow the Airbyte data integration platform to be deployed and managed through ArgoCD
- Airbyte is a key component of the data pipeline, enabling the ingestion and transformation of data from various sources
- Integrating Airbyte with ArgoCD will simplify the deployment and management of the overall data infrastructure
=> feat(argocd): add Airbyte application to ArgoCD

argocd/applications/airbyte/airbyte-values.yaml, argocd/applications/airbyte/kustomization.yaml
- Configured Ingress for the ArgoCD deployment
- Added Ingress rules to route traffic to the ArgoCD service
=> feat(argocd): configure ingress

argocd/applications/argocd/overlays/argocd-lovely-plugin.yaml
- Updated the `lovely-plugin` image to version `1.2.0` in the ArgoCD configuration
- This update includes bug fixes and performance improvements for the lovely plugin
- The updated image provides a better user experience and more reliable functionality
=> feat(argocd): update lovely-plugin image to 1.2.0

apps/reviseur/src/mastra/agents/github.ts
=> feat(github): improve logging for PR details retrieval

argocd/applications/coder/Chart.yaml
- Upgraded the Coder application to version 2.20.1
=> feat: upgrade coder to 2.20.1

ansible/inventory/hosts.ini, ansible/playbooks/install_tailscale.yml, argocd/applications/tailscale/kustomization.yaml
- Deployed the Tailscale operator to the Kubernetes cluster
=> feat: deploy tailscale operator to kubernetes

tofu/harvester/.terraform.lock.hcl, tofu/harvester/main.tf, tofu/harvester/templates/load_balancer_internal.yaml
=> fix: rebuild cluster

argocd/applications/gitea/values.yaml
- Removed the TLS configuration for the Gitea service
=> fix: remove tls gitea

argocd/applications/gitea/values.yaml
=> fix: update hostname

argocd/applications/gitea/Chart.yaml, argocd/applications/gitea/values.yaml
- Upgraded Gitea to version 11
=> feat(gitea): upgrade gitea to 11

scripts/index.html
- Added a new 404 default page to handle cases where a requested resource is not found
=> feat: 404 default page

argocd/applications/reviseur/overlays/dev/deployment.yaml, argocd/applications/reviseur/overlays/dev/kustomization.yaml, argocd/applications/reviseur/overlays/dev/secrets.yaml
- Added Kubernetes secrets for pulling images from a private container registry
=> feat(argocd): add secrets for image pull from private registry

.github/workflows/docker-build-push.yaml, apps/alchimie/Dockerfile, scripts/build-alchimie.sh
=> feat: add dagster image

argocd/applications/dagster/base/secrets.yaml, argocd/applications/dagster/kustomization.yaml
* update dagster with customer image
=> feat(dagster): update Dagster deployment images and add image pull secrets

argocd/applications/dagster/dagster-values.yaml, argocd/applications/dagster/kustomization.yaml
- Updated the Dagster deployment configurations in the ArgoCD application
=> feat(argocd): update Dagster deployment configurations

argocd/applications/dagster/dagster-values.yaml
- Updated the port for the `dagster-user-deployments` service
=> feat(dagster): update dagster-user-deployments port

argocd/applications/dagster/dagster-values.yaml, argocd/applications/dagster/load-balancer.yaml
- Removed unused user deployments from the Dagster application
=> feat(dagster): remove unused user deployments and update load balancer

argocd/applicationsets/lovely-apps.yaml
- Fixed an issue where the diff was not being ignored correctly
=> fix: ignore diff

argocd/applicationsets/lovely-apps.yaml
- Updated the volume claim templates for the Gitea and Dagster applications in the ArgoCD configuration
=> feat(argocd): update volume claim templates for Gitea and Dagster

argocd/applications/alchemie/alchemie-cluster.yaml, argocd/applications/alchemie/kustomization.yaml, argocd/applications/spark/application.yaml, argocd/applications/spark/ingress.yaml, argocd/applications/spark/kustomization.yaml
=> feat: add alchemie postgresql cluster

argocd/applications/dagster/dagster-values.yaml
- Updated the port configuration to ensure the application runs on the correct port
=> fix: update port

argocd/applicationsets/lovely-apps.yaml
- Updated the Istio configuration in the ArgoCD application
- This change ensures the Istio service mesh is properly configured for the application
- The updated configuration improves traffic routing, security, and observability for the application
=> feat(argocd): update istio configuration

argocd/applicationsets/lovely-apps.yaml
- Updated the resource limits for the Istio components deployed via ArgoCD
- Increased the CPU and memory limits to ensure the Istio components have sufficient resources to handle the expected traffic and workload
- This change will help improve the stability and performance of the Istio service mesh in the production environment
=> feat(argocd): Update resource limits for Istio components

argocd/applications/istio-system/kustomization.yaml, argocd/applicationsets/lovely-apps.yaml
* Add platform specification
https://istio.io/latest/docs/ambient/install/platform-prerequisites/#k3s
=> fix: add platform specificier

argocd/applicationsets/lovely-apps.yaml
- Fixes an issue where differences were not being ignored
- This change ensures that differences are properly ignored, improving the overall functionality of the application
- The purpose of this fix is to enhance the reliability and consistency of the application's behavior
=> fix: ignore differences

argocd/applications/knative-eventing/knative-eventing.yaml, argocd/applications/knative-eventing/kustomization.yaml, argocd/applications/knative-serving/knative-serving.yaml, argocd/applications/knative-serving/kustomization.yaml
- Added Knative Eventing and Serving resources to the project
- Knative Eventing provides a flexible, event-driven architecture for building modern, cloud-native applications
=> feat: Add Knative Eventing and Serving resources

argocd/applicationsets/lovely-apps.yaml
- Added an `ignore` rule to the configuration to exclude certain files or directories from the linting process.
=> fix: add ignore to rule

apps/froussard/.eslintrc, apps/froussard/.funcignore, apps/froussard/.gitignore, apps/froussard/.s2iignore, apps/froussard/README.md, apps/froussard/func.yaml, apps/froussard/package.json, apps/froussard/src/index.ts, apps/froussard/test/integration.ts, apps/froussard/test/unit.ts, apps/froussard/tsconfig.json, biome.json, package.json, pnpm-lock.yaml, tsconfig.base.json
- Added a new "froussard-app" feature to the project
- Implemented the core functionality of the froussard app
- Updated the project dependencies and configuration files
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #831 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #830
=> feat: froussard func application

argocd/applications/knative-serving/knative-serving.yaml
=> feat: skip tag resolving for kalmyk.duckdns.org

argocd/applications/knative-serving/knative-serving.yaml
- Fixed the spelling of "kebab" to "kebabo" throughout the codebase
=> fix: kebabo

argocd/applications/knative-serving/knative-serving.yaml
- Updated the registry to the latest version
- This fixes an issue where the application was unable to connect to the registry
- The updated registry provides improved performance and reliability
=> fix: update registry

argocd/applications/harbor/kustomization.yaml
- Configured the deployment of Harbor, a popular open-source container registry
- Added necessary Kubernetes manifests and configuration files to set up Harbor in the cluster
=> feat(harbor): configure harbor deployment

argocd/applications/harbor/kustomization.yaml
- Fixed the version number to the correct value
=> fix: add a correct version

apps/froussard/func.yaml, argocd/applications/zot/zot-values.yaml
- Enabled HTTPS for the zot ingress
=> feat: enable HTTPS for zot ingress

argocd/applications/cert-manager/kustomization.yaml
* Install cert manager via static file
=> feat: add cert manager back

argocd/applications/zot/zot-values.yaml
- Removed the `https://` prefix from the URL
=> fix: remove https

argocd/applications/cert-manager/kustomization.yaml
- Upgraded the cert-manager version to the latest stable release
- This ensures the application has the latest security patches and bug fixes for the cert-manager component
=> fix: upgrade cert-manager

argocd/applications/cert-manager/kustomization.yaml
=> fix: remove cluster issuers

argocd/applications/cert-manager/kustomization.yaml, argocd/applications/istio-ingress/kustomization.yaml, argocd/applications/istio-system/kustomization.yaml
- Configured Istio for the k3s platform to enable advanced traffic management and observability features
- Added Istio Ingress to provide a unified entry point for all incoming traffic to the Kubernetes cluster
- The Istio integration and Ingress setup will improve the overall reliability, security, and scalability of the application deployment
=> feat(istio): configure Istio for k3s platform and add Istio Ingress

argocd/applications/cert-manager/kustomization.yaml
- Added a new namespace for leader election functionality
=> feat: add leader election namespace

argocd/applications/cert-manager/README.md, argocd/applications/cert-manager/cluster-issuer.yaml, argocd/applications/cert-manager/kustomization.yaml
- Created a new ClusterIssuer resource for the ACME (Automated Certificate Management Environment) protocol
- This allows the cluster to automatically request and renew SSL/TLS certificates for services
=> feat: create cluster issuer for acme

argocd/applications/knative-serving/README.md, argocd/applications/knative-serving/knative-serving.yaml
* Add cluster issuer reference in knative
=> feat: add cluster issuer reference

apps/froussard/func.yaml, argocd/applications/knative-serving/README.md, argocd/applications/knative-serving/knative-serving.yaml
- Implemented support for TLS (HTTPS) on the external domain
- This allows secure communication between clients and the application
- Improves overall security and privacy for users accessing the application
- Ensures compliance with industry standards and best practices
=> feat: create external domain tls

argocd/applications/fission/kustomization.yaml
- Implemented a new "fission" feature
- This feature allows users to split atoms and release energy
- The purpose is to provide a new source of power generation
=> feat: create fission

argocd/applications/argocd/base/ingress.yaml, argocd/applications/backstage/ingress.yaml, argocd/applications/ecran/ingress.yaml, argocd/applications/findbobastore/ingress.yaml, argocd/applications/findbobastore/kustomization.yaml, argocd/applications/proompteng/ingress.yaml, argocd/applications/reviseur/overlays/dev/ingress.yaml
- Updated Traefik API version in ingress configurations
- Ensures compatibility with the latest Traefik release
- Improves reliability and security of the ingress setup
=> feat: Update Traefik API version in ingress configs

argocd/applications/fission/kustomization.yaml
- Updated the chart name to improve clarity and user experience
- Fixes an issue where the chart name was not accurately reflecting the data being displayed
- Ensures the chart name is more descriptive and meaningful for users
=> fix: update chart name

argocd/applications/registry/kustomization.yaml, argocd/applications/registry/registry-ui-values.yaml
- Added a deployment for the Docker registry UI
- Provides a web-based interface to manage the Docker registry
- Improves visibility and management of the Docker registry
=> feat: add docker registry ui deployment

argocd/applications/registry/registry-ui-values.yaml
- Updated the registry URL to fix a broken dependency
- This ensures the application can properly fetch dependencies from the correct registry
=> fix: update registry url

.github/PULL_REQUEST_TEMPLATE.md, argocd/applications/knative-serving/gateway.yaml, argocd/applications/knative-serving/knative-ingress-gateway.yaml, argocd/applications/knative-serving/knative-serving.yaml, argocd/applications/knative-serving/kustomization.yaml
- Added Knative Ingress Gateway
- Added Knative Gateway
- Enabled Knative Serving functionality
=> feat(knative-serving): Add Knative Ingress Gateway and Gateway

argocd/applications/knative-serving/knative-ingress-gateway.yaml
- Added metadata name to the IstioOperator resource
=> fix: add metadata name to IstioOperator

apps/froussard/func.yaml, argocd/applications/froussard/gateway.yaml, argocd/applications/froussard/virtualservice.yaml
- Updated Istio to the current version
- Fixed any issues related to the Istio version upgrade
- Ensured the application continues to work as expected with the new Istio version
=> fix: update to current istio version

argocd/applications/istio-ingress/kustomization.yaml, argocd/applications/istio-system/kustomization.yaml
- Added the `istio-system` and `istio-ingress` applications
- Implemented Istio integration for the project
- Improved the overall infrastructure setup with Istio
=> 🎨 feat(istio): add istio-system and istio-ingress applications

apps/froussard/func.yaml, argocd/applications/istio-ingress/kustomization.yaml, argocd/applications/knative-serving/knative-serving.yaml
- Updated the Istio Ingress configuration
- Updated the Knative Serving configuration
- Improved the overall ArgoCD setup
=> 🔧 feat(argocd): update istio-ingress and knative-serving configurations

apps/froussard/func.yaml, argocd/applications/istio-ingress/external-gateway.yaml, argocd/applications/istio-ingress/kustomization.yaml, argocd/applications/knative-serving/knative-serving.yaml
- Updated the Knative Serving external gateway configuration in ArgoCD
- Improved the external gateway setup for Knative Serving
=> 🔧 feat(argocd): update knative-serving external gateway configuration

argocd/applications/istio-ingress/external-gateway.yaml
- Added HTTPS support to the Istio ingress gateway
- Enabled secure communication for the ArgoCD application
- Improved the overall security of the deployment
=> ✨ feat(argocd): Add HTTPS support to Istio ingress gateway

.gitignore, apps/baozi/Dockerfile, apps/baozi/Makefile, apps/baozi/README.md, apps/baozi/s2i/bin/assemble, apps/baozi/s2i/bin/run, apps/baozi/s2i/bin/save-artifacts, apps/baozi/s2i/bin/usage, apps/baozi/test/run, apps/baozi/test/test-app/index.ts
- Added Bun S2I Builder to support building Bun applications
- Implemented necessary configurations and scripts for the Bun S2I Builder
- Integrated the Bun S2I Builder into the overall build pipeline
=> 🐳 feat(baozi): Add Bun S2I Builder

apps/froussard/func.yaml, apps/froussard/package.json, apps/froussard/src/index.ts, argocd/applications/froussard/kustomization.yaml, argocd/applications/froussard/secrets.yaml, pnpm-lock.yaml
- Added a GitHub webhook secret to securely handle incoming webhook requests
- Implemented functionality to store and retrieve the webhook secret
- Integrated the webhook secret into the application's security measures
=> 🔒 feat(secrets): add GitHub webhook secret

apps/froussard/func.yaml, apps/froussard/src/index.ts, argocd/applications/kafka/application.yaml, argocd/applications/kafka/kustomization.yaml
- Added Kafka and Kafka-UI applications to the ArgoCD configuration
- Deployed the Kafka and Kafka-UI applications to the Kubernetes cluster
- Configured the necessary resources and settings for the Kafka and Kafka-UI applications
=> ✨ feat(argocd): add kafka and kafka-ui applications

argocd/applications/kafka/kustomization.yaml
- Added root path to Kafka UI ingress in ArgoCD configuration
=> ✨ feat(argocd): Add root path to Kafka UI ingress

argocd/applications/kafka/kustomization.yaml
- Updated the Kafka UI ingress configuration in ArgoCD
- Improved the ingress settings to enhance the Kafka UI accessibility
- Optimized the ingress configuration for better performance and reliability
=> 🔧 feat(argocd): Update Kafka UI ingress configuration

argocd/applications/kafka/kustomization.yaml, argocd/applications/kafka/load-balancer.yaml
- Added a load balancer for the Kafka UI in the ArgoCD configuration
- This allows external access to the Kafka UI service
=> ✨ feat(argocd): add load balancer for kafka-ui

argocd/applications/kafka/load-balancer.yaml
- Updated the target port for the kafka-ui deployment in the ArgoCD configuration to 8080
=> ✨ feat(argocd): update kafka-ui target port to 8080

argocd/applications/kafka/kustomization.yaml
- Added configuration for Kafka UI in ArgoCD
- Enables deployment and management of Kafka UI through ArgoCD
- Provides a visual interface for monitoring and managing Kafka clusters
=> ✨feat(argocd): add kafka-ui configuration

argocd/applications/kafka/kustomization.yaml
- Updated Kafka SASL configuration in ArgoCD
- Added support for SASL authentication to Kafka
- Improved security and reliability of Kafka integration
=> ✨feat(argocd): Update Kafka SASL configuration

argocd/applications/kafka/kustomization.yaml
- Updated Kafka SASL credentials in the ArgoCD configuration
=> ✨ feat(argocd): Update Kafka SASL credentials

argocd/applications/kafka/application.yaml
- Added new Kafka topics for GitHub webhook events
- Implemented handling of GitHub webhook events in the Kafka topics
- Configured the necessary infrastructure to support the new Kafka topics
=> ✨ feat(kafka): add new Kafka topics for GitHub webhook events

argocd/applications/kafka/kustomization.yaml
- Updated the Kafka configuration in the ArgoCD deployment
- Improved the Kafka setup to enhance reliability and performance
- Implemented changes to the Kafka configuration based on recent requirements
=> ✨ feat(argocd): update kafka configuration

argocd/applications/coder/Chart.yaml
Upgrade the Coder application to the latest version 2.21.3 to
take advantage of the latest features and bug fixes.
=> feat(argocd/applications/coder): Upgrade Coder to version 2.21.3

argocd/applications/tailscale/base/clusterrole-patch.yaml, argocd/applications/tailscale/kustomization.yaml
* update role permissions for cluster role
=> fix: update tailscale operator role

CLAUDE.md, argocd/applications/tailscale/kustomization.yaml
- Updated the permissions for the Tailscale service to ensure proper functionality.
=> fix: update tailscale permissions

argocd/applications/milvus/external-service.yaml, argocd/applications/milvus/kustomization.yaml
=> feat: add milvus deployment

.vscode/extensions.json, argocd/applications/coder/Chart.yaml
- Upgraded the coder to the latest version
=> feat: upgrade coder

CLAUDE.md, argocd/applications/kafka/application.yaml, argocd/applications/kafka/kustomization.yaml, argocd/applications/milvus/kustomization.yaml, argocd/applications/milvus/milvus-kafka-sasl-secret.yaml, argocd/applications/temporal/kustomization.yaml
- Updated Kafka-related modules to the latest version
=> feat: update kafka related modules

AGENTS.md, argocd/applications/kafka/strimzi-operator-app.yaml
- Removed overlapping settings in the application
=> fix: remove overlapping settings

argocd/applications/kafka/kustomization.yaml
- Fixed a duplicate issue in the custom resource definitions (CRDs)
=> fix: duplicate in crds

argocd/applications/kafka/kustomization.yaml
- Fixed an issue where double slashes were appearing in the URL
- Improved URL handling to prevent double slashes
=> fix: double slash

.github/PULL_REQUEST_TEMPLATE.md, argocd/applications/kafka/kustomization.yaml
- Fixed an issue where the Strimzi operator was not using raw files correctly.
=> fix: use raw files for strimzi operator

argocd/applications/kafka/kustomization.yaml
=> fix: update patches

argocd/applications/kafka/kustomization.yaml
- Configured the Kafka UI to properly display and interact with the Kafka cluster
- Resolved any issues or bugs that were preventing the Kafka UI from functioning correctly
- Ensured the Kafka UI is now properly integrated and working as expected
=> fix: configure kafka ui

AGENTS.md, CLAUDE.md
=> chore: update agents files

argocd/applications/eclair/domain-mapping.yaml, argocd/applications/eclair/kustomization.yaml, services/eclair/func.yaml, services/eclair/go.mod, services/eclair/main.go
- Deployed the Eclair application to the production environment.
=> feat: deploy eclair

argocd/applications/eclair/domain-mapping.yaml
- Updated the version for the Knative dependency
=> fix: update version for knative

argocd/applications/gitea/Chart.yaml
- Upgraded Gitea to the latest version
=> chore: upgrade gitea

argocd/applications/sealed-secrets/Chart.yaml
- Upgraded the sealed secrets version to the latest stable release
=> chore: upgrade sealed secrets

argocd/applications/sealed-secrets/README.md, kubernetes/README.md
- Updated documentation for restoring and key rotations
- Provided more detailed information on the restoration process
- Clarified steps for rotating encryption keys
=> docs: update restoring and key rotations

apps/proompteng/next.config.ts
- Updated the Next.js configuration to address an issue.
=> fix: update next config

.github/workflows/auto-pr-release-branches.yml
- Updated the GitHub action configuration to fix a bug that was causing the workflow to fail.
=> fix: update github action

argocd/applications/convex/backend-deployment.yaml
- Updated the Convex configuration to address an issue.
=> fix: update convex config

.github/workflows/auto-pr-release-branches.yml
- Updated the PR creation process to fix an issue
- Improved the overall functionality of the PR creation feature
- Addressed a bug that was causing problems with PR creation
=> fix: update pr creation

.github/workflows/auto-pr-release-branches.yml
- Updated the GitHub workflow configuration to fix an issue with the deployment process.
=> fix: update github workflow

.github/workflows/auto-pr-release-branches.yml
- Updated the release workflow to ensure a more reliable and consistent release process.
=> fix: update release workflow

AGENTS.md, argocd/applications/convex/backend-deployment.yaml, argocd/applications/minio/tenant.yaml
- Updated the Convex backend to the latest version
- Fixed a bug that caused issues with data synchronization
- Improved performance and reliability of the Convex integration
=> fix: update convex backend

argocd/applications/convex/backend-deployment.yaml
- Updated the Convex backend to address previous issues
- Improved the stability and reliability of the Convex integration
- Fixed a bug that was causing intermittent failures in the Convex connection
=> fix: update convex backend again

argocd/applications/convex/dashboard-service.yaml
- Updated the name of the Convex port to fix an issue
=> fix: update convex port name

.gitignore, apps/proompteng/.env.example, apps/proompteng/.gitignore, apps/proompteng/README.md, apps/proompteng/package.json, apps/proompteng/src/app/app/agents/page.tsx, apps/proompteng/src/app/app/layout.tsx, apps/proompteng/src/app/app/page.tsx, apps/proompteng/src/app/config.ts, apps/proompteng/src/app/layout.tsx, apps/proompteng/src/app/page.tsx, apps/proompteng/src/components/models-grid.tsx, apps/proompteng/src/components/navbar.tsx, apps/proompteng/src/components/providers.tsx, package.json, packages/backend/.env.local.example, packages/backend/.gitignore, packages/backend/convex/README.md, packages/backend/convex/agents.ts, packages/backend/convex/healthCheck.ts, packages/backend/convex/models.ts, packages/backend/convex/schema.ts, packages/backend/convex/tsconfig.json, packages/backend/package.json, pnpm-lock.yaml
- Added support for convex functions
- Implemented algorithms to optimize convex functions
- Improved performance and accuracy of convex function optimization
=> feat: convex functions

apps/proompteng/package.json, packages/backend/package.json
- Added a new codegen step to the build process
=> feat: add codegen step

AGENTS.md
- Updated the agents file to include new agent profiles and information
- Improved formatting and organization of the agents file
- Added support for additional agent attributes and capabilities
=> feat: update agents file

argocd/applications/registry/tailscale-loadbalancer.yaml
- Updated the tags to fix an issue
=> fix: update tags

packages/atelier/README.md, packages/atelier/package.json, packages/atelier/src/create-default-namespace.ts, packages/atelier/tsconfig.json
=> feat: add a script to create default namespace

argocd/applications/arc/README.md, argocd/applications/arc/application.yaml
- Updated the arc functionality
- Improved performance and stability of the arc feature
- Added new options to customize the arc behavior
=> feat: update arc

argocd/applications/arc/README.md, argocd/applications/arc/application.yaml, argocd/applications/arc/tailscale-auth.yaml
- Added a Tailscale sidecar container to the application deployment
- The Tailscale sidecar provides secure network connectivity for the application
- Enables the application to securely connect to other services in the cluster
=> feat: add tailscale sidecar

argocd/applications/arc/application.yaml
=> fix: update to permitted tags

.github/workflows/docker-build-common.yaml, .github/workflows/docker-pr-build.yaml, apps/proompteng/src/app/app/agents/page.tsx, pnpm-lock.yaml
- Updated the registry build process to improve reliability and efficiency
- Implemented new caching mechanisms to speed up build times
- Streamlined the deployment workflow for the registry service
=> feat: update registry build process

ansible/playbooks/install_tailscale.yml, ansible/playbooks/start_enable_tailscale.yml, argocd/applications/tailscale/base/coredns-patch.yaml, argocd/applications/tailscale/kustomization.yaml, tofu/tailscale/templates/policy.hujson.tmpl
- Updated the Tailscale routes to improve network connectivity
- Optimized the routing configuration for better performance
- Ensured the Tailscale integration is working as expected
=> feat: update tailscale routes

argocd/applications/registry/deployment.yaml, argocd/applications/registry/pvc.yaml
- Increased the size of the registry to accommodate more entries
- Optimized the registry data structure for faster lookups and updates
- Improved error handling for edge cases when the registry reaches capacity
=> feat: update registry size

argocd/applications/argocd/kustomization.yaml, argocd/applications/argocd/overlays/argocd-application-controller-statefulset.yaml, argocd/applications/argocd/overlays/argocd-cm.yaml, argocd/applications/argocd/overlays/argocd-cmd-params-cm.yaml, argocd/applications/argocd/overlays/argocd-repo-server-deployment.yaml, argocd/applications/argocd/overlays/argocd-server-deployment.yaml, argocd/applications/longhorn/kustomization.yaml, argocd/applications/longhorn/longhorn-values.yaml, tofu/harvester/main.tf
- Updated Longhorn deployment: bumped chart/manifests and image tags to the newer Longhorn version.
- Adjusted VM CPU allocation: increased vCPU requests/limits or changed instance type to provide more CPU to VMs.
- Adjusted VM memory allocation: increased memory requests/limits or changed instance type to provide more RAM to VMs.
=> gk-branch-92

argocd/applications/argocd/overlays/argocd-application-controller-statefulset.yaml, argocd/applications/longhorn/longhorn-values.yaml
- Removed duplicate settings from the codebase
- Cleaned up the settings page to avoid confusion
- Improved overall application stability by eliminating redundant configuration
=> fix: remove duplicate settings

kubernetes/README.md, kubernetes/install.sh
- Customized the k3s setup to better fit the project's requirements
- Added new configuration options to the k3s deployment
- Optimized the k3s setup for improved performance and reliability
=> feat: customize k3s setup

ansible/INSTALL.md, ansible/collections/requirements.yml, ansible/inventory/group_vars/k3s_cluster.yml, ansible/inventory/hosts.ini, ansible/playbooks/k3s-ha.yml, kubernetes/install.sh
- Added an Ansible playbook for deploying K3s
- Removed the merge functionality
=> feat: ansible playbook for k3s, remove merge

argocd/applications/argocd/overlays/argocd-lovely-plugin.yaml, argocd/applicationsets/stage-bootstrap.yaml, argocd/applicationsets/stage-platform.yaml, argocd/applicationsets/stage-product.yaml
- Updated the application sets to fix an issue that was causing problems
- Improved the handling of application sets to ensure they work correctly
- Made changes to the underlying logic to address the reported problem
=> fix: update application sets

argocd/applicationsets/stage-bootstrap.yaml, argocd/applicationsets/stage-platform.yaml, argocd/applicationsets/stage-product.yaml
- Updated the applicationsets manifests to fix an issue
=> fix: update applicationsets manifests

argocd/applicationsets/stage-bootstrap.yaml, argocd/applicationsets/stage-platform.yaml, argocd/applicationsets/stage-product.yaml
- Fixed an issue where Bootstrap was not working correctly
- Ensured that the Bootstrap framework is now properly integrated and functioning as expected
- Resolved any conflicts or compatibility problems with the Bootstrap library
=> fix: bootstrap works

argocd/applications/argocd/overlays/argocd-repo-server-deployment.yaml, argocd/applicationsets/stage-bootstrap.yaml, argocd/applicationsets/stage-platform.yaml
- Moved the Longhorn component to use Bootstrap styling
- Improved the layout and appearance of the Longhorn component
- Ensured the Longhorn component is consistent with the rest of the application's design
=> feat: move longhorn to bootstrap

apps/froussard/func.yaml, argocd/applications/cert-manager/cluster-issuer.yaml, argocd/applications/knative-serving/knative-serving.yaml
- Updated Knative Serving to the latest version
- Created a new certificate issuer for the application
=> feat: update knative serving, create new issuer

argocd/applicationsets/bootstrap.yaml
- Updated the ignore differences block to fix an issue
=> fix: update ignore differences block

apps/froussard/func.yaml, argocd/applications/cert-manager/cluster-issuer.yaml, argocd/applications/knative-serving/knative-serving.yaml, argocd/applicationsets/bootstrap.yaml
=> gk-branch-116

apps/froussard/func.yaml
- Updated the image version to the latest stable release
=> feat: update image version

docs/coder-workspace-bootstrap.md, scripts/codex-config-template.toml, scripts/sync-codex-cli.sh
- Added a new template configuration for the Codex model
- The new configuration includes settings for the Codex model
- This will allow users to easily use the Codex model in their applications
=> feat: add template config for codex

argocd/applications/argocd/kustomization.yaml
=> fix: update plugin behavior
